### ISSUE TITLE
延迟加载清单

### ISSUE THREAD

**Issue by shuch** [shuch/blog#26]
## 图片延迟加载
* `IntersectionObserver`
```js
const observer = new IntersectionObserver((entries) => {
  const image = entries[0];
  if (image.isIntersecting) {
      setLoading(false);
      observer.unobserve(ref.current);
  }
});

observer.observe(ref.current);
```
* `getBoundingClientRect`
```js
function elementInViewport(el) {
  var rect = el.getBoundingClientRect()
  return (
     rect.top >= 0
     && rect.left >= 0
     && rect.top <= (window.innerHeight || document.documentElement.clientHeight)
 )
}
```
## `JavaScript`延迟加载
* `react`中的`suspense`
* `ES6`动态 `import()`

```js
const ProfilePage = React.lazy(() => import('./ProfilePage')); // 懒加载

// 在 ProfilePage 组件处于加载阶段时显示一个 spinner
<Suspense fallback={<Spinner />}>
  <ProfilePage />
</Suspense>
```

## 字体延迟加载
`font-display`

```css
@font-face {
  font-family: 'MyWebFont'; /* Define the custom font name */
  src:  url('myfont.woff2') format('woff2'),
        url('myfont.woff') format('woff'); /* Define where the font can be downloaded */
  font-display: fallback; /* Define how the browser behaves during download */
}
```

## 参考
* [Intersection Observer](https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver)
* [用于数据获取的 Suspense](https://zh-hans.reactjs.org/docs/concurrent-mode-suspense.html)
* [font-display](https://css-tricks.com/almanac/properties/f/font-display/)
